GET http://localhost:3000/news

###

POST  http://localhost:3000/news
Content-Type: application/json

{
    "title": "News 8",
    "text": "Text for news 2",
    "img": "path",
    "id_user": null,
    "isActive": 1
}

###

DELETE http://localhost:3000/news

###

GET http://localhost:3000/news/4

###

PUT http://localhost:3000/news/2
Content-Type: application/json

{
    "title": "News 20",
    "text": "Text for news 20"
}

###

DELETE http://localhost:3000/news/4