GET http://localhost:3000/categories

###

GET http://localhost:3000/categories/5

###

POST  http://localhost:3000/categories
Content-Type: application/json

{
    "Name": "Some category"
}

###

DELETE http://localhost:3000/categories

###

DELETE http://localhost:3000/categories/14

###

PUT http://localhost:3000/categories/15
Content-Type: application/json

{
    "Name": "Some category updated"
}